# https://pub.dev/packages/package_rename
package_rename_config:
  android:
    app_name: Tekio
    package_name: tekio.app.playground
    # override_old_package: com.example.example
    # lang: kotlin

  ios:
    app_name: Tekio
    bundle_name: tekio
    package_name: tekio.app.playground

  web:
    app_name: Tekio
    description: Just my tekio app playground

  linux:
    app_name: Tekio
    package_name: tekio.app.playground
    exe_name: tekioappplayground

  windows:
    app_name: Tekio
    organization: Tekio Dev
    copyright_notice: Copyright ©️ 2022 TekioDev. All rights reserved.
    exe_name: tekioappplayground

  macos:
    app_name: Tekio
    package_name: tekio.app.playground
    copyright_notice: Copyright ©️ 2022 TekioDev. All rights reserved.