name: playground_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_remote_config: ^5.4.0
  firebase_analytics: ^11.4.2
  firebase_auth: ^5.4.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  go_router: ^14.8.0
  logging: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  get_it: ^8.0.3
  sembast: ^3.8.3
  path_provider: ^2.1.5
  path: ^1.9.0
  encrypt: ^5.0.3
  reactive_forms: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  package_rename: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/



