// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAug4X01HR_xoH1J_M4bb0EcjLzS1pP2AI',
    appId: '1:71218859180:web:dfe521dabfde5c6a096309',
    messagingSenderId: '71218859180',
    projectId: 'playground-dev-firebase',
    authDomain: 'playground-dev-firebase.firebaseapp.com',
    storageBucket: 'playground-dev-firebase.firebasestorage.app',
    measurementId: 'G-9PBMH18CKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrf9k6OrHXephaVDd6ndU_qoIYSeDB0Yc',
    appId: '1:71218859180:android:ff24c93c943709e1096309',
    messagingSenderId: '71218859180',
    projectId: 'playground-dev-firebase',
    storageBucket: 'playground-dev-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh7QzzSIWkEa1v-_p53iqEw7Tw9Ni3Uc8',
    appId: '1:71218859180:ios:849858a54c5dd7db096309',
    messagingSenderId: '71218859180',
    projectId: 'playground-dev-firebase',
    storageBucket: 'playground-dev-firebase.firebasestorage.app',
    iosBundleId: 'com.example.playgroundFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh7QzzSIWkEa1v-_p53iqEw7Tw9Ni3Uc8',
    appId: '1:71218859180:ios:849858a54c5dd7db096309',
    messagingSenderId: '71218859180',
    projectId: 'playground-dev-firebase',
    storageBucket: 'playground-dev-firebase.firebasestorage.app',
    iosBundleId: 'com.example.playgroundFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAug4X01HR_xoH1J_M4bb0EcjLzS1pP2AI',
    appId: '1:71218859180:web:7b5cf4b3a3545ab3096309',
    messagingSenderId: '71218859180',
    projectId: 'playground-dev-firebase',
    authDomain: 'playground-dev-firebase.firebaseapp.com',
    storageBucket: 'playground-dev-firebase.firebasestorage.app',
    measurementId: 'G-NYK1EDSWTZ',
  );

}