// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TekioBackend.Setup;

#nullable disable

namespace TekioBackend.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20250504203827_MoreSimpleModel")]
    partial class MoreSimpleModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TekioBackend.AppConfig.AppConfigData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppName")
                        .HasColumnType("text");

                    b.Property<string>("MainColor")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("SupportedLocales")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("AppConfigData");
                });
#pragma warning restore 612, 618
        }
    }
}
